
--1
INSERT INTO MOVIESTAR(NAME, BIRTHDATE)
VALUES('Nicole Kidman', '1967-06-20')

--2
--DELETE FROM MOVIE
--WHERE PRODUCERC# IN (
--SELECT CERT# FROM MOVIEEXEC
--WHERE NETWORTH < 30000000
--)

--deleting the dependencies we cannot remove a row with FK 
--without deleting and the row in the other relation where it the FK points to

DELETE FROM MOVIEEXEC
WHERE NETWORTH < 30000000

--3
DELETE FROM MOVIESTAR
WHERE ADDRESS IS NULL


--4
INSERT INTO PRODUCT(MODEL, MAKER, TYPE)
VALUES('1100', 'C', 'PC')

INSERT INTO PC(CODE, MODEL, SPEED, RAM, HD, CD, PRICE)
VALUES(12, '1100', 2400, 2048, 500, '52x', 299)

--5
DELETE FROM PRODUCT
WHERE MODEL = '1100'

DELETE FROM PC
WHERE MODEL = '1100'

--6
DELETE FROM PRODUCT 
WHERE TYPE = 'Laptop' AND MAKER NOT IN (SELECT MAKER FROM PRODUCT
WHERE TYPE = 'Printer')

DELETE FROM LAPTOP
WHERE MODEL IN (SELECT MODEL FROM PRODUCT 
WHERE TYPE = 'Laptop' AND MAKER NOT IN (SELECT MAKER FROM PRODUCT
WHERE TYPE = 'Printer'))

--7
UPDATE PRODUCT 
SET MAKER = 'A' 
WHERE MAKER = 'B'

--8
UPDATE PC
SET PRICE = PRICE/2

UPDATE PC
SET HD = HD + 20

--9
UPDATE LAPTOP
SET SCREEN = SCREEN + 1
WHERE MODEL IN (SELECT MODEL FROM PRODUCT
WHERE MAKER = 'B' AND TYPE = 'Laptop')


--10
INSERT INTO CLASSES(CLASS, TYPE, COUNTRY, NUMGUNS, BORE, DISPLACEMENT)
VALUES('Nelson-Nelson', 'bb', 'Gt. Britain', 9, 16, 34000)

INSERT INTO CLASSES(CLASS, TYPE, COUNTRY, NUMGUNS, BORE, DISPLACEMENT)
VALUES('Rodney', 'bb', 'Gt. Britain', 9, 16, 34000)

INSERT INTO SHIPS(NAME, CLASS, LAUNCHED)
VALUES('Neli', 'Nelson-Nelson', 1927)

INSERT INTO SHIPS(NAME, CLASS, LAUNCHED)
VALUES('Radi', 'Rodney', 1927)

--11
DELETE FROM SHIPS 
WHERE NAME IN (SELECT SHIP FROM OUTCOMES
WHERE RESULT = 'sunk')

DELETE FROM OUTCOMES
WHERE RESULT = 'sunk'

--12
UPDATE CLASSES
SET BORE =  2.5 * BORE

UPDATE CLASSES
SET DISPLACEMENT = DISPLACEMENT / 1.1  
