
--WEEK NINE
------------------------------------------------------------


WITH FOO AS
(
(SELECT EMPLOYEEID, FIRSTNAME, LASTNAME, TITLE, REPORTSTO, LVL AS 0
FROM EMPLOYEES
WHERE REPORTSTO IS NULL)
UNION ALL --COMBINES BASE CASE WITH THE RECURSIVE TABLE
(SELECT E.EMPLOYEEID,E.FIRSTNAME,E.LASTNAME,E.REPORTSTO,
(FOO.LVL + 1) LVL
FROM FOO
INNER JOIN EMPLOYEES E ON E.REPORTSTO = FOO.EMPLOYEEID
)
)
SELECT * FROM FOO

--DROP TABLE - IT ELIMINATES/REMOVES THE TABLE
--TRUNCATE - REALLY FAST TO EMPTY A TABLE
--BACKUS-NAUR
--ALTER TABLE - MODIFY THE TABLE
--ADD
--DROP
--DEFAULT VALUE - NULL

USE FOO;
CREATE TABLE MOVIE(
TITLE VARCHAR(20),
YEAR INT,
LENGTH INT,
COLOR CHAR(1)
CONSTRAINT UC_MOVIE1 UNIQUE(TITLE, YEAR)
CONSTRAINT PK_MOVIE_17 PRIMARY KEY(TITLE, YEAR)
)
--VARCHAR - STORES MUCH SPACE AS NEEDED
--NOT WASTING SPACE

DROP TABLE STAR;
CREATE TABLE STAR(
NAME VARCHAR(20) UNIQUE,
BIRTHDATE DATE,
ADDRESS VARCHAR(40)
CONSTRAINT PK_STAR_1 PRIMARY KEY(NAME)
)

--CONSTRAINTS
--UNIQUE -> THIS COLUMN WILL ONLY STORES UNIQUE VALUES
--CAN WE HAVE NULL -> ONLY ONE TIME -> IT TREATS AS A UNIQUE
--CHECK -> GIVING RESTRICTION TO THE DATA

DROP TABLE SI;
CREATE TABLE SI(
ID INT IDENTITY PRIMARY KEY
MTITLE VARCHAR(20),
MYEAR INT,
SNAME VARCHAR(20)
CONSTRAINT FK_SI_3 FOREIGN KEY REFERENCES STAR(NAME)
--WE CAN MAKE CONSTRAINT PRIMARY KEY(MTITLE,MYEAR,SNAME)
)
--WHEN INSERTING FK WITH REFERENCES TABLE_COLUMN -> IF THIS WASNT INSERTED IN THE REF TABLE
--THEN, WE ARE NOT ALLOWED TO INSERT IN THE SI/MAINN/ TABLE
--ON DELETE NO ACTION
--ON DELETE SET NULL - WHEN WE DELETE THE NAME IN THE REF TABLE -> BEHIND THE FK WE WILL GET NULL

CREATE TABLE TRACK(
USERNAME VARCHAR(8),
PROJECTNAME VARCHAR(8),
STARTDATE DATE,
ENDDATE DATE,
)

INSERT INTO TRACK(USERNAME, PROJECTNAME, STARTDATE, ENDDATE)
VALUES('Harry', 'PC', '1942-11-15', '1942-11-16')

INSERT INTO TRACK(USERNAME, PROJECTNAME, STARTDATE, ENDDATE)
VALUES('Jack', 'PC', '1942-05-15', '1942-06-16')

INSERT INTO TRACK(USERNAME, PROJECTNAME, STARTDATE, ENDDATE)
VALUES('Jack', 'PRINTER', '1942-05-15', '1942-11-16')

INSERT INTO TRACK(USERNAME, PROJECTNAME, STARTDATE, ENDDATE)
VALUES('Gogo', 'PRINTER', '1940-05-15', '1942-11-16')
--()
SELECT *, DATEDIFF(day, STARTDATE, ENDDATE) AS DURATION FROM TRACK

WITH WORKING_HOURS AS
(SELECT TONE.USERNAME AS USER_ONE, TTWO.USERNAME AS USER_TWO, SUM(DATEDIFF(day, GREATEST(TONE.STARTDATE, TTWO.STARTDATE), LEAST(TONE.ENDDATE, TTWO.ENDDATE))) 
AS D FROM TRACK TONE
CROSS JOIN TRACK TTWO
WHERE TONE.USERNAME != TTWO.USERNAME AND TONE.USERNAME < TTWO.USERNAME

AND TONE.PROJECTNAME = TTWO.PROJECTNAME
GROUP BY TONE.USERNAME,TTWO.USERNAME )

SELECT USER_ONE, USER_TWO, D FROM WORKING_HOURS
WHERE D = (SELECT MAX(D) FROM WORKING_HOURS)
--SELECT MAX(D) FROM WORKING_HOURS

--USERNAME AND PROJECTNAME NOT NULL
--START_DATE NOT NULL
--ALL FOUR COLUMNS DEFINE THE PRIMARY KEY
--ONE EMPLOYEE CAN WORK MULTIPLE TIMES ON THE SAME PROJECT
--START_DATE <= END_DATE
--CAN NOT WORKING INTERVALS OVERLAP -> 20-24 APRIL PESHO AND 21-23 APRIL PESHO -> NOT VALID

-- QUERY WHICH PAIR OF PROGRAMMERS HAVE WORKED TOGETHER THE MOST TIME - X DAYS / SUM OF ALL INTERVALS


--Task One
CREATE TABLE PRODUCT(
MAKER CHAR(1),
MODEL CHAR(4),
TYPE VARCHAR(7)
);

CREATE TABLE PRINTER(
CODE INT, 
MODEL CHAR(4),
PRICE DECIMAL(10, 2)
);

INSERT INTO PRODUCT(MAKER, MODEL, TYPE)
VALUES('A', '5555', 'CHOCO')

INSERT INTO PRODUCT(MAKER, MODEL, TYPE)
VALUES('B', '5556', 'WAFFLE')

INSERT INTO PRODUCT(MAKER, MODEL, TYPE)
VALUES('B', '5566', 'PANCAKE')

INSERT INTO PRINTER(CODE, MODEL, PRICE)
VALUES(5, 'A', 55.5)

INSERT INTO PRINTER(CODE, MODEL, PRICE)
VALUES(6, 'B', 555.5)

ALTER TABLE PRINTER ADD TYPE VARCHAR(6) CHECK (TYPE IN ('laser', 'matrix', 'jet'))
ALTER TABLE PRINTER ADD COLOR CHAR(1) CHECK (COLOR IN ('n', 'y'))

ALTER TABLE PRINTER DROP COLUMN PRICE

DROP TABLE PRINTER
DROP TABLE PRODUCT

--Task Two
CREATE TABLE USERS(
ID INT UNIQUE,
EMAIL VARCHAR(15),
PASSWORD VARCHAR(16),
DATE_RES DATETIME,
)

CREATE TABLE FRIENDS(
USER_ONE INT,
USER_TWO INT
)

CREATE TABLE WALLS(
USER_ID INT,
USER_ID_MSG INT,
MSG VARCHAR(55),
DATE DATETIME
)

CREATE TABLE GROUPS(
GROUP_ID INT UNIQUE,
NAME VARCHAR(15),
DESCRIPTION VARCHAR(55) DEFAULT '',
)

CREATE TABLE GROUPMEMBERS(
GROUP_ID INT UNIQUE,
USER_ID INT UNIQUE,
)

INSERT INTO USERS(ID, EMAIL,PASSWORD,DATE_RES)
VALUES(5, 'LOLO.gmail', 'hello', '1979-07-05')

INSERT INTO USERS(ID, EMAIL,PASSWORD,DATE_RES)
VALUES(6, 'hoho.gmail', 'hello', '1979-07-05')

INSERT INTO FRIENDS(USER_ONE, USER_TWO)
VALUES(5,6)

INSERT INTO WALLS(USER_ID, USER_ID_MSG, MSG, DATE)
VALUES(5, 6, 'JHSHJSUYSYSGFTYSH HSFYS', '1979-07-05')

INSERT INTO GROUPS(GROUP_ID, NAME, DESCRIPTION)
VALUES(55, 'GAME', 'A GAME IS DEELOPED...')

INSERT INTO GROUPMEMBERS(GROUP_ID, USER_ID)
VALUES(55, 5)

INSERT INTO GROUPMEMBERS(GROUP_ID, USER_ID)
VALUES(55, 6)

--Task three
CREATE TABLE AIRLINE(
CODE INT CONSTRAINT PK_AIRLINE PRIMARY KEY,
NAME VARCHAR(15) UNIQUE NOT NULL,
COUNTRY VARCHAR(15)
)

CREATE TABLE AIRPORT(
CODE INT CONSTRAINT PK_AIRPORT PRIMARY KEY,
NAME VARCHAR(15) NOT NULL,
COUNTRY VARCHAR(15),
CITY VARCHAR(15),
UNIQUE (NAME, COUNTRY)
)

CREATE TABLE AIRPLANE(
CODE INT CONSTRAINT PK_AIRPLANE PRIMARY KEY,
TYPE VARCHAR(15),
SEATS INT CHECK (SEATS >= 0),
YEAR INT,
)

CREATE TABLE CUSTOMER(
ID INT CONSTRAINT PK_CUSTOMER PRIMARY KEY,
FNAME VARCHAR(15),
LNAME VARCHAR(15),
EMAIL VARCHAR(55) CHECK (EMAIL LIKE '%@%.%' AND LENGTH(EMAIL) >= 6) 
)

CREATE TABLE AGENCY(
NAME VARCHAR(15) CONSTRAINT PK_AGENCY PRIMARY KEY,
COUNTRY VARCHAR(15),
CITY VARCHAR(15),
PHONE VARCHAR(15),
)

CREATE TABLE BOOKING(
--CODE INT CONSTRAINT PK_BOOKING PRIMARY KEY,
FOREIGN KEY (CODE) INT REFERENCES FLIGHT(FNUMBER) NOT NULL,
FOREIGN KEY (AGENCY_NAME) VARCHAR(15) REFERENCES AGENCY(NAME) NOT NULL,
FOREIGN KEY (AIRLINE_CODE) INT REFERENCES AIRLINE(CODE) NOT NULL,
FLIGHT_NUMBER INT NOT NULL,
FOREIGN KEY (CUSTOMER_ID) INT REFERENCES CUSTOMER(ID) NOT NULL,
BOOKING_DATE DATETIME CHECK (BOOKING_DATE <= FLIGHT_DATE),
FLIGHT_DATE DATETIME,
PRICE DECIMAL NOT NULL,
STATUS INT CHECK (STATUS IN (1,0))
) NOT NULL

CREATE TABLE FLIGHT(
FNUMBER INT CONSTRAINT PK_FLIGHT PRIMARY KEY,
FOREIGN KEY (AIRLINE_OPERATOR) INT REFERENCES AIRLINE(CODE) NOT NULL,
FOREIGN KEY (DEP_AIRPORT) INT REFERENCES AIRPORT(CODE) NOT NULL,
FOREIGN KEY (ARR_AIRPORT) INT REFERENCES AIRPORT(CODE) NOT NULL,
FLIGHT_TIME DATETIME,
FLIGHT_DURATION INT NOT NULL,
FOREIGN KEY (AIRPLANE) INT REFERENCES AIRPLANE(CODE) NOT NULL,
)

ALTER TABLE FLIGHT
ADD CONSTRAINT FOREIGN KEY (AIRLINE_OPERATOR) INT REFERENCES AIRLINE(CODE) NOT NULL


