
--1
CREATE TABLE CUSTOMER(
CUSTOMER_ID INT IDENTITY(1,1) PRIMARY KEY,
CUSTOMER_NAME VARCHAR(100),
CUSTOMER_ADDRESS VARCHAR(100),
CUSTOMER_CITY VARCHAR(100),
CITY_CODE VARCHAR(5),
);

CREATE TABLE ORDER_T(
ORDER_ID INT PRIMARY KEY,
ORDER_DATE DATE,
CUSTOMER_ID INT CONSTRAINT FK_CUSTOMER
REFERENCES CUSTOMER(CUSTOMER_ID)
);


CREATE TABLE PRODUCT(
PRODUCT_ID INT PRIMARY KEY,
PRODUCT_DESCREPTION VARCHAR(100),
PRODUCT_FINISH  VARCHAR(100),
STANDART_PRICE FLOAT,
PRODUCT_LINE_ID INT,

CONSTRAINT CHK_FINISH
CHECK (
PRODUCT_FINISH IN (
'череша',
'естествен ясен',
'бял ясен',
'червен дъб', 
'естествен дъб',
'орех'
)
)
);


CREATE TABLE ORDER_LINE(
ORDER_ID INT CONSTRAINT FK_ORDERT
REFERENCES ORDER_T(ORDER_ID),
PRODUCT_ID INT CONSTRAINT FK_PR
REFERENCES PRODUCT(PRODUCT_ID),
ORDERED_QUANTITY INT
);

--2
SELECT P.PRODUCT_ID, P.PRODUCT_DESCREPTION , COUNT(*) AS ORDER_NUMBER FROM PRODUCT P
INNER JOIN ORDER_LINE O ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_DESCREPTION

--3
SELECT  P.PRODUCT_ID, P.PRODUCT_DESCREPTION ,COALESCE(SUM(O.ORDERED_QUANTITY), 0) FROM PRODUCT P
LEFT OUTER JOIN ORDER_LINE O ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_DESCREPTION

--4
SELECT C.CUSTOMER_NAME , SUM(O.ORDERED_QUANTITY * P.STANDART_PRICE) AS TOTAL_PRICE FROM CUSTOMER C
INNER JOIN ORDER_T T ON T.CUSTOMER_ID = C.CUSTOMER_ID
INNER JOIN ORDER_LINE O ON O.ORDER_ID = T.ORDER_ID
INNER JOIN PRODUCT P ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY C.CUSTOMER_NAME


--5
--WITH INTERSECTION
SELECT DISTINCT(P.MAKER)  FROM PRODUCT P
INNER JOIN PC A ON A.MODEL = P.MODEL
INTERSECT 
SELECT DISTINCT(P.MAKER) FROM PRODUCT P
INNER JOIN LAPTOP L ON L.MODEL = P.MODEL

--WITH SUBQUERY
SELECT DISTINCT(P.MAKER) FROM PRODUCT P
INNER JOIN PC A ON A.MODEL = P.MODEL
WHERE P.MAKER IN (
SELECT DISTINCT(P.MAKER) FROM PRODUCT P
INNER JOIN LAPTOP L ON L.MODEL = P.MODEL
)

--6
UPDATE PC
SET PRICE = PRICE * 0.95
FROM PC
JOIN PRODUCT P ON P.MODEL = PC.MODEL
WHERE P.MAKER IN 
(SELECT P.MAKER FROM PRODUCT P
INNER JOIN PRINTER PR ON PR.MODEL = P.MODEL
GROUP BY P.MAKER
HAVING AVG(PR.PRICE) >= 800)

--7
SELECT HD ,MIN(PRICE) AS MIN_PRICE FROM PC
WHERE HD >= 10 AND HD <= 30
GROUP BY HD


--8
--a/
--CREATE VIEW more_ships AS
SELECT B.NAME FROM BATTLES B
INNER JOIN OUTCOMES O ON O.BATTLE = B.NAME
GROUP BY B.NAME
HAVING COUNT(*)  > (SELECT COUNT(*) FROM OUTCOMES O
INNER JOIN BATTLES B ON B.NAME = O.BATTLE
WHERE B.NAME = 'Guadalcanal');

--b/
--CREATE VIEW more_countries AS
SELECT B.NAME ,COUNT(DISTINCT C.COUNTRY) FROM BATTLES B
INNER JOIN OUTCOMES O ON O.BATTLE = B.NAME
INNER JOIN SHIPS S ON S.NAME = O.SHIP
INNER JOIN CLASSES C ON C.CLASS = S.CLASS
GROUP BY B.NAME
HAVING  COUNT(DISTINCT C.COUNTRY) > (
   SELECT COUNT(DISTINCT C.COUNTRY) FROM BATTLES B
    INNER JOIN OUTCOMES O ON O.BATTLE = B.NAME
    INNER JOIN SHIPS S ON S.NAME = O.SHIP
    INNER JOIN CLASSES C ON C.CLASS = S.CLASS
   WHERE B.NAME = 'Guadalcanal'
   GROUP BY B.NAME
)

--9
DELETE FROM OUTCOMES 
WHERE BATTLE IN 
(
SELECT BATTLE FROM OUTCOMES
GROUP BY BATTLE
HAVING COUNT(*) = 1
)

--10
DELETE FROM OUTCOMES
WHERE RESULT = 'sunk' AND SHIP IN 
(
SELECT SHIP FROM OUTCOMES
WHERE RESULT = 'sunk'
GROUP BY SHIP
HAVING COUNT(*) >= 2
)

--11
CREATE VIEW battles_cntrs AS
SELECT B.NAME, C.COUNTRY FROM BATTLES B
INNER JOIN OUTCOMES O ON O.BATTLE = B.NAME
INNER JOIN SHIPS S ON S.NAME = O.SHIP
INNER JOIN CLASSES C ON C.CLASS = S.CLASS
GO


SELECT DISTINCT A.NAME FROM battles_cntrs A
WHERE NOT EXISTS (
SELECT COUNTRY FROM battles_cntrs
WHERE NAME = A.NAME
EXCEPT
SELECT COUNTRY FROM battles_cntrs
WHERE NAME = 'Guadalcanal'

)
AND NOT EXISTS(
SELECT COUNTRY FROM battles_cntrs
WHERE NAME = 'Guadalcanal'
EXCEPT
SELECT COUNTRY FROM battles_cntrs
WHERE NAME = A.NAME
)
AND A.NAME != 'Guadalcanal'

--EXCEPT GIVES AS THE DIFFERENCE A\B AND THEN WE CHECK
--WHETHER IS THE EMPTY SET B\A SO IF A\B AND B\A ARE THE EMPTY SET 
--THIS MEANS A = B

--12
SELECT C.COUNTRY, COALESCE(COUNT(DISTINCT B.NAME), 0) FROM CLASSES C
LEFT OUTER JOIN SHIPS S ON C.CLASS = S.CLASS
LEFT OUTER JOIN OUTCOMES O ON S.NAME = O.SHIP
LEFT OUTER JOIN BATTLES B ON O.BATTLE = B.NAME
GROUP BY C.COUNTRY

