
--indexes
--1
CREATE VIEW TASK_ONE AS
SELECT AGENCY, FLIGHT_NUMBER, COUNT(CUSTOMER_ID) AS CUSTOMER_COUNT FROM BOOKINGS
WHERE STATUS = 1
GROUP BY AGENCY, FLIGHT_NUMBER

--2
CREATE VIEW TASK_TWO AS
WITH HELPER AS(
SELECT AGENCY, COUNT(FLIGHT_NUMBER) AS C FROM BOOKINGS
GROUP BY AGENCY)
SELECT MAX(C) FROM HELPER;

--2.1
CREATE VIEW TASK_TWO AS
WITH HELPER AS(
SELECT AGENCY, COUNT(FLIGHT_NUMBER) AS C FROM BOOKINGS
GROUP BY AGENCY)
SELECT MAX(C) FROM HELPER;

--(WITH HELPER AS(
SELECT T.FNAME, T.LASTNAME FROM
(SELECT B.AGENCY, C.FNAME, C.LNAME, COUNT(FLIGHT_NUMBER) AS CNT FROM BOOKINGS B
INNER JOIN CUSTOMERS C ON C.ID = B.CUSTOMER_ID
GROUP BY B.AGENCY, C.FNAME, C.LNAME) AS T
INNER JOIN (SELECT T.AGENCY, MAX(T.CNT) AS MAXI FROM T 
GROUP BY T.AGENCY) S ON S.AGENCY = T.AGENCY 
WHERE T.CNT = S.MAXI 
--)
--SELECT AGENCY, MAX(CNT) FROM HELPER
--GROUP BY AGENCY) AS T

SELECT T.AGENCY, T.FNAME, T.LNAME 
FROM (
SELECT B.AGENCY, C.FNAME, C.LNAME, COUNT(*) AS CNT
FROM BOOKINGS B
JOIN CUSTOMERS C ON C.ID = B.CUSTOMER_ID
GROUP BY B.AGENCY, C.FNAME, C.LNAME
) T
JOIN (
SELECT AGENCY, MAX(CNT) AS MAXI
FROM (
SELECT B.AGENCY, C.FNAME, C.LNAME, COUNT(B.FLIGHT_NUMBER) AS CNT
FROM BOOKINGS B
JOIN CUSTOMERS C ON C.ID = B.CUSTOMER_ID
GROUP BY B.AGENCY, C.FNAME, C.LNAME
) X
GROUP BY AGENCY
) S
ON T.AGENCY = S.AGENCY AND T.CNT = S.MAXI

--3
CREATE VIEW SOFIA_AGENCIES AS
SELECT * FROM AGENCIES
WHERE CITY = 'Sofia'
WITH CHECK OPTION;

--4
CREATE VIEW AGENCIES_NO_PHONE AS
SELECT * FROM AGENCIES
WHERE PHONE IS NULL
WITH CHECK OPTION
--with check option we cannot insert/update data that
--doesnt satisfy this condition

--6
--when we have only where clauses - we can change the data in the view
--but if we have aggregate and group functions we cannot make changes

--7
DROP AGENCIES_NO_PHONE;
DROP SOFIA_AGENCIES;
DROP TASK_ONE;
DROP TASK_TWO;

--creating indexes
CREATE INDEX IDX_PC_MODEL ON PC(MODEL)
CREATE INDEX IDX_MODEL ON PRODUCT(MODEL)
CREATE INDEX IDX_SHIP ON OUTCOMES(SHIP)
CREATE INDEX IDX_CLASS_SHIPS ON SHIPS(CLASS)
CREATE INDEX IDX_CLASS_CLASSES ON CLASSES(CLASS)
CREATE INDEX IDX_NAME ON BATTLES(NAME)
CREATE INDEX IDX_NAME_BATTLE ON OUTCOMES(BATTLE)

--DROPPING THE INDEXES
DROP INDEX IDX_PC_MODEL ON PC;
DROP INDEX IDX_MODEL ON PRODUCT;
DROP INDEX IDX_CLASS_SHIPS ON OUTCOMES;
DROP INDEX IDX_NAME ON BATTLES;
DROP INDEX IDX_CLASS_SHIPS ON OUTCOMES;
DROP INDEX IDX_NAME_BATTLE ON OUTCOMES;
