--One
ALTER TABLE FLIGHTS
ADD NUM_PASS INT DEFAULT 0;

UPDATE FLIGHTS F
SET NUM_PASS = (
SELECT COUNT(*) FROM BOOKINGS B
WHERE B.FLIGHT_NUMBER = F.FNUMBER
AND B.STATUS = 1
);

--Two

ALTER TABLE AGENCIES
ADD NUM_BOOK INT DEFAULT 0;

UPDATE AGENCIES A
SET NUM_BOOK = (
SELECT COUNT(*) FROM BOOKINGS B
WHERE A.AGENCY = B.AGENCY
AND B.STATUS = 1
);

--Three
CREATE TRIGGER TRG_INSERT
ON BOOKINGS
AFTER INSERT
AS
BEGIN
   
   UPDATE F
   SET F.NUM_PASS = F.NUM_PASS + 1
   FROM FLIGHTS F
   INNER JOIN INSERTED I ON
   I.FLIGHT_NUMBER = F.FNUMBER;

   UPDATE A
   SET A.NUM_BOOK = A.NUM_BOOK + 1
   FROM AGENCIES A
   INNER JOIN INSERTED I ON
   I.AGENCY = A.AGENCY;
END;

--Four
CREATE TRIGGER TRG_DELETE
ON BOOKINGS
AFTER DELETE
AS
BEGIN
   
   UPDATE F
   SET F.NUM_PASS = F.NUM_PASS - 1
   FROM FLIGHTS F
   INNER JOIN DELETED D ON
   D.FNUMBER = F.FNUMBER;

   UPDATE A
   SET F.NUM_BOOK = F.NUM_BOOK - 1
   FROM AGENCIES A
   INNER JOIN DELETED D ON
   D.AGENCY = A.AGENCY;
END;

--Five
CREATE TRIGGER TRG_UPDATE
ON BOOKINGS
AFTER UPDATE
AS
BEGIN
   
   UPDATE F
   SET F.NUM_PASS = F.NUM_PASS + 1
   FROM FLIGHTS F
   INNER JOIN INSERTED I ON F.NUMBER = I.FLIGHT_NUMBER
   INNER JOIN DELETED D ON D.CODE = I.CODE
   WHERE D.STATUS = 0 AND I.STATUS = 1;

   
   UPDATE F
   SET F.NUM_PASS = F.NUM_PASS - 1
   FROM FLIGHTS F
   INNER JOIN INSERTED I ON F.NUMBER = I.FLIGHT_NUMBER
   INNER JOIN DELETED D ON D.CODE = I.CODE
   WHERE D.STATUS = 1 AND I.STATUS = 0;

END;
