--WEEK 5 TASKS
SELECT AVG(LENGTH) FROM MOVIE
SELECT MIN(LENGTH) FROM MOVIE
SELECT MAX(LENGTH) FROM MOVIE

-- we cant use * when using group by
SELECT * FROM MOVIE
ORDER BY STUDIONAME

SELECT STUDIONAME,COUNT(TITLE) CT
FROM MOVIE
GROUP BY STUDIONAME

SELECT YEAR(BIRTHDATE) YD FROM MOVIESTAR
--count* - gets all the rows
--zadachi week5
--1
SELECT AVG(SPEED) FROM PC

--2
SELECT P.MAKER, AVG(L.SCREEN) FROM PRODUCT P
INNER JOIN LAPTOP L ON L.MODEL = P.MODEL
GROUP BY MAKER

--3
SELECT AVG(L.SPEED) FROM LAPTOP L
WHERE L.PRICE > 1000

--4
SELECT AVG(P1.PRICE) FROM PRODUCT P
INNER JOIN PC P1 ON P1.MODEL = P.MODEL
GROUP BY MAKER
HAVING MAKER ='A'

--5
SELECT T.MAKER, AVG(PRICE) FROM
(SELECT MAKER, PRICE FROM PRODUCT P
INNER JOIN PC P1 ON P1.MODEL = P.MODEL
UNION ALL
SELECT MAKER, PRICE FROM PRODUCT P
INNER JOIN LAPTOP L ON L.MODEL = P.MODEL) T
WHERE MAKER = 'B'
GROUP BY MAKER

--having maker = 'B'

--6
SELECT SPEED, AVG(P.PRICE) FROM PC P
GROUP BY P.SPEED

--7
SELECT P.MAKER, COUNT(C.MODEL) AS NUMBERPC FROM PRODUCT P
INNER JOIN PC C ON C.MODEL = P.MODEL
GROUP BY MAKER
HAVING COUNT(C.MODEL) >= 3

--8
SELECT P.MAKER ,PRICE FROM PRODUCT P
INNER JOIN PC P1 ON P1.MODEL = P.MODEL
WHERE PRICE = (SELECT MAX(PRICE) FROM PC)

--9
SELECT SPEED, AVG(PRICE) AS AVGPRICE FROM PC
WHERE SPEED > 800
GROUP BY SPEED

--10
SELECT MAKER, AVG(C.HD) FROM PRODUCT P
INNER JOIN PC C ON C.MODEL = P.MODEL
WHERE P.MAKER IN (SELECT MAKER FROM PRODUCT P1
INNER JOIN PRINTER D ON D.MODEL = P1.MODEL)
GROUP BY MAKER

--zadachi
--1
SELECT COUNT(CLASS) FROM CLASSES
WHERE TYPE='bb'

--2
SELECT CLASS, AVG(NUMGUNS) FROM CLASSES
WHERE TYPE = 'bb'
GROUP BY CLASS

--3
SELECT AVG(NUMGUNS) AS AVGNUMGUNS FROM CLASSES
WHERE TYPE = 'bb'

--4
SELECT C.CLASS, MIN(LAUNCHED) AS FIRSTYEAR, MAX(LAUNCHED) AS LASTYEAR FROM CLASSES C
INNER JOIN SHIPS S ON S.CLASS = C.CLASS
GROUP BY C.CLASS

--5
SELECT C.CLASS, COUNT(SHIP) AS COUNTSUNK FROM CLASSES C
INNER JOIN SHIPS S ON S.CLASS = C.CLASS
INNER JOIN OUTCOMES O ON O.SHIP = S.NAME
WHERE RESULT = 'sunk'
GROUP BY C.CLASS

--6
SELECT T.CLASS, COUNT(SHIP) AS NO_SUNK FROM (SELECT CLASS FROM CLASSES C
WHERE C.CLASS IN (SELECT C1.CLASS FROM
CLASSES C1 
INNER JOIN SHIPS S1 ON S1.CLASS = C1.CLASS
GROUP BY C1.CLASS
HAVING COUNT(S1.NAME) > 2) ) T
INNER JOIN SHIPS S ON S.CLASS = T.CLASS
INNER JOIN OUTCOMES O ON O.SHIP = S.NAME
WHERE O.RESULT = 'sunk'
GROUP BY T.CLASS


--7
SELECT COUNTRY, ROUND(AVG(BORE), 2) FROM CLASSES
GROUP BY COUNTRY
