12:05
--Test preparation

--1 - count all the sunk ships for each class
SELECT C.CLASS, COUNT(S.NAME) AS NUMBER FROM CLASSES C
INNER JOIN SHIPS S ON S.CLASS = C.CLASS
INNER JOIN OUTCOMES O ON O.SHIP = S.NAME
WHERE O.RESULT = 'sunk'
GROUP BY C.CLASS

--better version
--WE skip the classes where he ships aren't sunk
--the WHERE clause removes them
SELECT C.CLASS, COUNT(S.NAME) AS NUMBER FROM CLASSES C
LEFT OUTER JOIN SHIPS S ON S.CLASS = C.CLASS
LEFT OUTER JOIN OUTCOMES O ON O.SHIP = S.NAME
WHERE O.RESULT = 'sunk' OR S.NAME IS NULL
GROUP BY C.CLASS

--SOLVE THE PROBLEM WITH CASE
SELECT C.CLASS,
SUM(CASE RESULT
WHEN 'sunk' THEN 1
ELSE 0
END) SUNK_COUNT
FROM CLASSES C
LEFT OUTER JOIN SHIPS S ON S.CLASS = C.CLASS
LEFT OUTER JOIN OUTCOMES O ON O.SHIP = S.NAME
GROUP BY C.CLASS

--COALESCE - CHOOSES THE FIRST NOT NULL VALUE

--get the date and count the number of sunk,damaged,ok ships per class
SELECT B.NAME, MIN(B.DATE),
SUM(CASE O.RESULT
WHEN 'sunk' THEN 1
ELSE 0
END) SUNK_COUNT,
SUM(CASE O.RESULT
WHEN 'ok' THEN 1
ELSE 0
END) OK_COUNT,
SUM(CASE O.RESULT
WHEN 'damaged' THEN 1
ELSE 0
END) DAMAGED_COUNT
FROM BATTLES B
LEFT OUTER JOIN OUTCOMES O ON B.NAME = O.BATTLE
GROUP BY B.NAME,B.DATE

--GETTING THE COUNT OF CLASSES WITH >= 4 SHIPS ON WATER
SELECT CLASS
FROM SHIPS
GROUP BY CLASS
HAVING COUNT(NAME) >= 4

SELECT S.CLASS,
SUM(CASE RESULT
WHEN 'sunk' THEN 1
ELSE 0
END) IS_SUNK
FROM SHIPS S
INNER JOIN OUTCOMES O ON S.NAME = O.SHIP
GROUP BY S.CLASS
HAVING S.CLASS IN (

SELECT CLASS
FROM SHIPS
GROUP BY CLASS
HAVING COUNT(NAME) >= 4

)

--SECOND VERSION
SELECT S.CLASS, S.NAME, O.BATTLE,
SUM(CASE RESULT
WHEN 'sunk' THEN 1
ELSE 0
END) SUM_SUNK,
COUNT(DISTINCT S.NAME) CN
FROM SHIPS S
INNER JOIN OUTCOMES O ON S.NAME = O.SHIP
GROUP BY S.CLASS
HAVING COUNT(DISTINCT S.NAME) >= 4


--ADD NEW COLUMN
SELECT *, 'FOO' AS BAR, GENDER FROM MOVIESTAR

--CREATES A NEW COLUMN
SELECT *, 'FOO' AS BAR, GENDER,
CASE GENDER
WHEN 'm' then 'MALE'
WHEN 'f' then 'FEMALE'
ELSE 'UNKNOWN'
END CAT
FROM MOVIESTAR
SELECT *,
CASE
WHEN PRICE < 900 THEN 'LOW'
WHEN PRICE > 1100 THEN 'HIGH'
ELSE 'AVERAGE'
END PR
FROM PC
SELECT BIRTHDATE,
CASE
WHEN YEAR(BIRTHDATE) < 1960 THEN 'BEFORE 1960'
WHEN YEAR(BIRTHDATE) >= 1960 AND YEAR(BIRTHDATE) < 1970 THEN '60s'
WHEN YEAR(BIRTHDATE) >= 1970 AND YEAR(BIRTHDATE) < 1980 THEN '70S'
else 'after 1979'
end cd
FROM MOVIESTAR

--GET THE BATTLES WHERE WE HAVE AT LEAST TWO OK SHIPS AND HAVE PARTICIPATED >= 3 SHIPS
SELECT O.BATTLE, COUNT(S.NAME),
SUM(CASE O.RESULT
WHEN 'ok' THEN 1
ELSE 0
END) IS_OK_COUNT FROM OUTCOMES O
INNER JOIN SHIPS S ON S.NAME = O.SHIP
INNER JOIN CLASSES C ON C.CLASS = S.CLASS
WHERE C.NUMGUNS < 10
GROUP BY O.BATTLE
HAVING COUNT(S.NAME) >= 3 AND SUM(CASE O.RESULT
WHEN 'ok' THEN 1
ELSE 0
END) >= 2

--FOR EACH CLASS, COUNTRY GET THE YEAR OF THE FIRST LAUNCHED
SELECT C.CLASS, C.COUNTRY, MIN(S.LAUNCHED)
FROM CLASSES C
INNER JOIN SHIPS S ON C.CLASS = S.CLASS
GROUP BY C.CLASS, C.COUNTRY

--GET THE SHIPS THAT HAVE PARTICIPATED IN BATTLES IN AT LEAST TWO DIFFERENT YEARS
SELECT O.SHIP, COUNT(DISTINCT YEAR(DATE)) CD
FROM OUTCOMES O
INNER JOIN BATTLES B ON O.BATTLE = B.NAME
GROUP BY O.SHIP
HAVING COUNT(DISTINCT YEAR(DATE)) >= 2

-- GET THE SHIPS WHERETHE DELTA BETWEEN FIRST AND LAST BATTLE IS >= 1
SELECT O.SHIP, MAX(YEAR(DATE)) - MIN(YEAR(DATE)) DELTA
FROM OUTCOMES O
INNER JOIN BATTLES B ON O.BATTLE = B.NAME
GROUP BY O.SHIP
HAVING MAX(YEAR(DATE)) - MIN(YEAR(DATE)) >= 1


--COUNT THE SHIPS PER YEAR
SELECT DISTINCT YEAR(DATE) FROM BATTLES B

SELECT LAUNCHED, COUNT(NAME) CN FROM SHIPS S
WHERE LAUNCHED IN (SELECT DISTINCT YEAR(DATE) FROM BATTLES B)
GROUP BY LAUNCHED

--GET THE DIFF BETWEEN BETWEEN LAUNCHED
SELECT ship, YEAR(DATE) - S.LAUNCHED delta
FROM OUTCOMES O
INNER JOIN SHIPS S ON S.NAME = O.SHIP
INNER JOIN BATTLES B ON O.BATTLE = B.NAME
WHERE RESULT = 'sunk'


  --Exam prep - one
  --1
  SELECT TITLE, YEAR,LENGTH 
  FROM MOVIE
  WHERE (LENGTH > 120 OR LENGTH IS NULL) AND (YEAR IS NULL OR YEAR < 2000) 

  --2
  SELECT NAME, GENDER 
  FROM MOVIESTAR
  WHERE NAME  LIKE 'J%' AND YEAR(BIRTHDATE) > 1948
  ORDER BY NAME DESC

  --3
  SELECT M.STUDIONAME, COUNT(DISTINCT A.STARNAME) AS NUMACT FROM STUDIO S
  INNER JOIN MOVIE M ON S.NAME = M.STUDIONAME
  INNER JOIN STARSIN A ON A.MOVIETITLE = M.TITLE
  GROUP BY M.STUDIONAME

 --4
 SELECT S.NAME, COUNT(DISTINCT M.TITLE) AS NUM_MOV FROM STARSIN A
 INNER JOIN MOVIE M ON M.TITLE = A.MOVIETITLE
 RIGHT OUTER JOIN MOVIESTAR S ON S.NAME = A.STARNAME
 GROUP BY S.NAME

 --5
 SELECT S.NAME, M.TITLE, M.YEAR FROM STUDIO S
 INNER JOIN MOVIE M ON M.STUDIONAME = S.NAME
 WHERE M.YEAR >= ALL(
 SELECT N.YEAR
 FROM MOVIE N
 INNER JOIN STUDIO K ON K.NAME = N.STUDIONAME
 WHERE S.NAME = K.NAME)

 --6
 SELECT A.NAME FROM MOVIESTAR A
 WHERE A.BIRTHDATE >= ALL(SELECT BIRTHDATE FROM MOVIESTAR)

 --7
 SELECT T.NAME, T.STARNAME, T.NUM_MOV
 FROM
    (SELECT S.NAME,A.STARNAME, COUNT(A.MOVIETITLE) AS NUM_MOV 
    FROM STUDIO S
    INNER JOIN MOVIE M ON M.STUDIONAME = S.NAME
    INNER JOIN STARSIN A ON A.MOVIETITLE = M.TITLE
    GROUP BY S.NAME, A.STARNAME) T
 WHERE T.NUM_MOV >= ALL  
    (SELECT COUNT(A.MOVIETITLE) AS NUM_MOV FROM STUDIO S
    INNER JOIN MOVIE M ON M.STUDIONAME = S.NAME
    INNER JOIN STARSIN A ON A.MOVIETITLE = M.TITLE
    WHERE M.STUDIONAME = T.NAME
    GROUP BY S.NAME, A.STARNAME)

 --8
SELECT M.TITLE ,M.YEAR, COUNT(S.STARNAME) AS NUM_ACT FROM MOVIE M
INNER JOIN STARSIN S ON S.MOVIETITLE = M.TITLE
GROUP BY M.TITLE, M.YEAR
HAVING COUNT(S.STARNAME) > 2


--Exam prep one
--9
SELECT S.NAME FROM SHIPS S
INNER JOIN OUTCOMES O ON O.SHIP = S.NAME
WHERE S.NAME LIKE 'K%' OR S.NAME LIKE 'C%' 
GROUP BY S.NAME
HAVING COUNT(O.SHIP) >= 1

--10
SELECT C.COUNTRY, S.NAME FROM CLASSES C
INNER JOIN SHIPS S ON S.CLASS = C.CLASS
LEFT OUTER JOIN OUTCOMES O ON O.SHIP = S.NAME
WHERE O.RESULT IS NULL OR O.RESULT != 'sunk'

--11
--for countries with no ships at all
SELECT C.COUNTRY, COUNT(O.RESULT) AS NUM_SUNK FROM CLASSES C
LEFT OUTER JOIN SHIPS S ON S.CLASS = C.CLASS
LEFT OUTER JOIN OUTCOMES O ON O.SHIP = S.NAME
WHERE O.RESULT = 'sunk' OR O.RESULT IS NULL
GROUP BY C.COUNTRY

--12
SELECT O.BATTLE FROM SHIPS S
INNER JOIN OUTCOMES O ON O.SHIP = S.NAME
GROUP BY O.BATTLE
HAVING COUNT(O.SHIP) > (SELECT COUNT(I.NAME) FROM SHIPS I
INNER JOIN OUTCOMES OI ON OI.SHIP = I.NAME
WHERE OI.BATTLE = 'Guadalcanal')

--13
SELECT O.BATTLE FROM OUTCOMES O
INNER JOIN SHIPS S ON S.NAME = O.SHIP
INNER JOIN CLASSES C ON C.CLASS = S.CLASS
GROUP BY O.BATTLE
HAVING COUNT(C.COUNTRY) > (SELECT COUNT(CO.COUNTRY) FROM CLASSES CO
INNER JOIN SHIPS SO ON SO.CLASS = CO.CLASS
INNER JOIN OUTCOMES OO ON OO.SHIP = SO.NAME
WHERE OO.BATTLE = 'Surigao Strait')

--14
SELECT T.NAME, T.DISPLACEMENT,T.NUMGUNS FROM (SELECT S.NAME, C.DISPLACEMENT, C.NUMGUNS FROM SHIPS S
INNER JOIN CLASSES C ON C.CLASS = S.CLASS
WHERE C.DISPLACEMENT <= ALL (SELECT DISPLACEMENT FROM CLASSES)) T
WHERE T.NUMGUNS >= ALL
    (SELECT C.NUMGUNS FROM SHIPS S
    INNER JOIN CLASSES C ON C.CLASS = S.CLASS
    WHERE C.DISPLACEMENT <= 
    ALL (SELECT DISPLACEMENT FROM CLASSES))

--15
SELECT COUNT(S.NAME) AS NUM_SHIPS FROM SHIPS S
INNER JOIN OUTCOMES O ON O.SHIP = S.NAME
INNER JOIN BATTLES B ON B.NAME = O.BATTLE
WHERE B.DATE > 
    ANY(SELECT BI.DATE FROM SHIPS SI
    INNER JOIN OUTCOMES OI ON OI.SHIP = SI.NAME
    INNER JOIN BATTLES BI ON BI.NAME = OI.BATTLE
    WHERE OI.RESULT = 'damaged' AND SI.NAME = S.NAME)

--16
--selects number of ships per battle
SELECT O.BATTLE, B.DATE, COUNT(O.SHIP) AS NUM FROM SHIPS S
INNER JOIN OUTCOMES O ON O.SHIP = S.NAME
INNER JOIN BATTLES B ON B.NAME = O.BATTLE
GROUP BY O.BATTLE,B.DATE

SELECT O.BATTLE, B.DATE, S.NAME FROM SHIPS S
INNER JOIN OUTCOMES O ON O.SHIP = S.NAME
INNER JOIN BATTLES B ON B.NAME = O.BATTLE
WHERE O.RESULT = 'damaged'

--SOLUTION
SELECT DISTINCT OI.SHIP
FROM OUTCOMES OI
JOIN (
  SELECT BATTLE, COUNT(*) AS SIZE
  FROM OUTCOMES
  GROUP BY BATTLE
) TONE
ON OI.BATTLE = TONE.BATTLE
JOIN OUTCOMES OE ON OE.SHIP = OI.SHIP
JOIN (
  SELECT BATTLE, COUNT(*) AS SIZE
  FROM OUTCOMES
  GROUP BY BATTLE
) TTWO
  ON TTWO.BATTLE = OE.BATTLE
JOIN BATTLES BONE 
  ON BONE.NAME = OI.BATTLE
JOIN BATTLES BTWO
  ON BTWO.NAME = OE.BATTLE
WHERE OI.RESULT = 'damaged'
AND OE.RESULT != 'damaged' 
AND TONE.SIZE < TTWO.SIZE
AND BONE.DATE < BTWO.DATE


--Exam prep one
--17
SELECT MODEL,CODE,SCREEN FROM LAPTOP
WHERE SCREEN = 11 OR SCREEN = 15

--18
SELECT DISTINCT P.MODEL FROM PC P
INNER JOIN PRODUCT K ON K.MODEL = P.MODEL
WHERE P.PRICE < (SELECT L.PRICE FROM LAPTOP L
                INNER JOIN PRODUCT D ON D.MODEL = L.MODEL
                WHERE L.PRICE <= ALL(SELECT L2.PRICE FROM LAPTOP L2
                                   INNER JOIN PRODUCT H ON H.MODEL = L2.MODEL
                                    WHERE H.MAKER = K.MAKER)
                 AND D.MAKER = K.MAKER)

--19
SELECT P.MODEL,AVG(P.PRICE) AS AVRG FROM PC P
INNER JOIN PRODUCT N ON N.MODEL = P.MODEL
GROUP BY P.MODEL, N.MAKER
HAVING AVG(P.PRICE) < (SELECT MIN(W.PRICE) FROM LAPTOP W
INNER JOIN PRODUCT F ON F.MODEL = W.MODEL
WHERE F.MAKER = N.MAKER)


--20
SELECT P.CODE, N.MAKER, 
(SELECT COUNT(*) FROM PC PO 
WHERE PO.PRICE >= P.PRICE) AS NUM_HIGH
FROM PC P
INNER JOIN PRODUCT N ON N.MODEL = P.MODEL
