
  --week 3 
--IT WILL GET NOTHING CAUSE THE BIGGEST > BIGGEST
SELECT * FROM MOVIEEXEC MX1
WHERE MX1.NETWORTH >= ALL (SELECT NETWORTH FROM MOVIEEXEC MX2)

--THE SUBQUERY DOESN'T SEE THE QUERY - IT WORKS LIKE THE SCOPES


--IT WILL SELECT ONLY THE MOVIES WITH A FEW VERSIONS
--IF WE HAVE ONLY ONE MOVIE -> 1977 < 1977? -> NO BUT 1916 < ANY(1977,..) -> YES
SELECT * FROM MOVIE M1
WHERE M1.YEAR < ANY(SELECT YEAR FROM MOVIE M2
WHERE M2.TITLE = M1.TITLE)

SELECT * FROM STARSIN

SELECT * FROM MOVIESTAR MS
WHERE MS.GENDER = 'M'

--JOIN ONLY THE MALE ACTORS
--WE MUST WRITE NAME - T
SELECT * FROM STARSIN SI
JOIN (SELECT * FROM MOVIESTAR MS WHERE MS.GENDER = 'M') T
ON SI.STARNAME = T.NAME

--ZADACHI WEEK 3
--1
SELECT MS.NAME FROM MOVIESTAR MS
JOIN (SELECT NAME FROM MOVIEEXEC EX
WHERE EX.NETWORTH > 10000000) T ON MS.NAME = T.NAME

--2
SELECT NAME FROM MOVIESTAR MS
WHERE MS.NAME NOT IN (SELECT NAME FROM MOVIEEXEC)

--3
SELECT TITLE FROM MOVIE M1
WHERE M1.LENGTH > (SELECT LENGTH FROM MOVIE M2
WHERE M2.TITLE = 'Star Wars')

--4
SELECT MV.TITLE,EX.NAME FROM MOVIE MV
JOIN MOVIEEXEC EX ON EX.CERT# = MV.PRODUCERC#
WHERE EX.NETWORTH > (SELECT NETWORTH FROM MOVIEEXEC EX2
WHERE EX2.NAME = 'Merv Griffin')


--week 3
--SELECT THE MOST EXPENSIVE PRINTER
SELECT * FROM PRINTER P1
WHERE P1.PRICE >= ALL (SELECT PRICE FROM PRINTER P2)

--SELECT ONLY ONE PRINTER
SELECT * FROM PRINTER P3
WHERE P3.CODE <= ALL (SELECT P1.CODE FROM PRINTER P1
WHERE P1.PRICE >= ALL (SELECT PRICE FROM PRINTER P2)
)

--IT WONT BE VALID IF THE PRINTER WITH THE BIGGEST PRICE IS WITH LESS CODE
SELECT * FROM PRINTER P1
WHERE P1.PRICE >= ALL (SELECT P2.PRICE FROM PRINTER P2)
AND P1.CODE <= ALL(SELECT P3.CODE FROM PRINTER P3
WHERE P3.PRICE = P1.PRICE)
--WE GET THE HIGHEST PRICE -> THEN WE GET ALL THE MATCHING OBJECTS WITH THE SAME PRICE
--AND THEN WE GET THE CODE SMALLER THAN THE SELECTED CODES OF THE PRINTERS WITH THE SAME PRICE

SELECT 'FOO' A

SELECT 'FOO' A
FROM PRINTER M1
WHERE M1.PRICE < 500

--ZADACHI WEEK 3
--1
SELECT DISTINCT P.MAKER FROM PRODUCT P
JOIN (SELECT * FROM PC P1
WHERE P1.SPEED > 500) T ON T.MODEL = P.MODEL

--2
SELECT P1.CODE,P1.MODEL,P1.PRICE FROM PRINTER P1
WHERE P1.PRICE >= ALL (SELECT PRICE FROM PRINTER P2)

--3
SELECT * FROM LAPTOP L
WHERE L.SPEED < ALL(SELECT SPEED FROM PC)

--4
SELECT P.MODEL, T.PRICE FROM PRODUCT P,
(SELECT MODEL, PRICE FROM PC
UNION 
SELECT MODEL, PRICE FROM LAPTOP
UNION 
SELECT MODEL, PRICE FROM PRINTER) T 
WHERE T.MODEL = P.MODEL AND T.PRICE >= ALL (
(SELECT PRICE FROM PC
UNION 
SELECT PRICE FROM LAPTOP
UNION 
SELECT PRICE FROM PRINTER)
)
--5
SELECT P.MAKER FROM PRODUCT P
JOIN (SELECT * FROM PRINTER PR) T ON T.MODEL = P.MODEL
WHERE T.COLOR = 'y' AND T.PRICE <= ALL(SELECT PRICE FROM PRINTER PR2
WHERE PR2.COLOR = 'y')
--better version
SELECT P.MAKER FROM PRODUCT P
JOIN PRINTER PR ON PR.MODEL = P.MODEL
WHERE PR.COLOR = 'y'
AND PR.PRICE <= ALL(SELECT PRICE FROM PRINTER PR2
WHERE PR2.COLOR = 'y')

--WHERE T.PRICE <= ALL(SELECT PRICE FROM PRINTER PR1
--WHERE PR1.COLOR = 'y')

--6
SELECT P.MAKER FROM PRODUCT P
JOIN PC C ON C.MODEL = P.MODEL
WHERE C.RAM <= ALL(SELECT RAM FROM PC C2)
AND C.SPEED >= ALL(SELECT SPEED FROM PC C3
WHERE C.RAM = C3.RAM)


--week 3
SELECT * FROM OUTCOMES
SELECT * FROM SHIPS

SELECT O.*,
(SELECT LAUNCHED FROM SHIPS S WHERE S.NAME = O.SHIP) Y
FROM OUTCOMES O

--1
SELECT DISTINCT COUNTRY FROM CLASSES C
WHERE C.NUMGUNS >= ALL(SELECT NUMGUNS FROM CLASSES)

--2
SELECT DISTINCT C.CLASS FROM SHIPS C
JOIN OUTCOMES BT ON BT.SHIP = C.NAME
WHERE EXISTS (SELECT * FROM OUTCOMES BT1
WHERE BT1.RESULT = 'sunk' AND C.NAME = BT1.SHIP)

--better version
SELECT DISTINCT C.CLASS FROM SHIPS C
WHERE EXISTS (SELECT * FROM OUTCOMES BT1 
WHERE BT1.RESULT = 'sunk' AND BT1.SHIP = C.NAME)

--3
SELECT S.NAME,C.CLASS FROM SHIPS S
JOIN CLASSES C ON C.CLASS = S.CLASS
WHERE C.BORE = 16

--4
SELECT B.BATTLE FROM OUTCOMES B
WHERE EXISTS (SELECT * FROM SHIPS S
WHERE S.NAME = B.SHIP 
AND S.CLASS = 'Kongo')

--5
SELECT C.CLASS, S.NAME FROM SHIPS S
JOIN CLASSES C ON C.CLASS = S.CLASS
WHERE C.NUMGUNS >= ALL(SELECT NUMGUNS FROM CLASSES C2
WHERE C.BORE = C2.BORE)



