
SELECT *
FROM MOVIESTAR MS
INNER JOIN MOVIEEXEC ME ON MS.NAME = ME.NAME

--IZVEJDA SAMO EDNITE IMENA
SELECT MS.NAME,MS.BIRTHDATE,ME.NETWORTH
FROM MOVIESTAR MS
FULL OUTER JOIN MOVIEEXEC ME ON MS.NAME = ME.NAME

--COALESCE - RETURNS THE FIRST NOT NULL VALUE FROM THE (..)
SELECT *, COALESCE(MS.NAME,ME.NAME) FOO
FROM MOVIESTAR MS
FULL OUTER JOIN MOVIEEXEC ME ON MS.NAME = ME.NAME

--IZVEDETE IMENATA I COUNTRY NA KORABITE, KOITO NE SA UCHASTVALI V BITKA
SELECT C.COUNTRY, S.NAME
FROM SHIPS S
INNER JOIN CLASSES C ON S.CLASS = C.CLASS
LEFT OUTER JOIN OUTCOMES O ON S.NAME = O.SHIP
WHERE O.BATTLE IS NULL

SELECT S.CLASS, B.NAME FROM SHIPS S
INNER JOIN CLASSES C ON C.CLASS = S.CLASS
LEFT OUTER JOIN OUTCOMES ON S.NAME = O.SHIP
INNER JOIN BATTLES B ON B.NAME = O.BATTLE

--one idea
SELECT DISTINCT S.CLASS, B.NAME FROM SHIPS S
INNER JOIN CLASSES C ON C.CLASS = S.CLASS
LEFT OUTER JOIN OUTCOMES O ON S.NAME = O.SHIP
LEFT OUTER JOIN BATTLES B ON B.NAME = O.BATTLE
WHERE C.COUNTRY = 'Gt.Britain'

--second idea
SELECT DISTINCT C.CLASS, O.BATTLE
FROM CLASSES C
LEFT OUTER JOIN SHIPS S ON C.CLASS = S.CLASS
LEFT OUTER JOIN OUTCOMES O ON O.SHIP = S.NAME
WHERE C.COUNTRY = 'Gt.Britain'

--SOLUTION
SELECT *
FROM OUTCOMES O
INNER JOIN SHIPS S ON O.SHIP = S.NAME
RIGHT OUTER JOIN CLASSES C ON C.CLASS = S.CLASS
WHERE C.COUNTRY = 'Gt.Britain'
--right outer join to see and the classes whose ships havent participated in battles

--equavalent
SELECT *
FROM CLASSES C
LEFT OUTER JOIN (
SELECT * FROM OUTCOMES O
INNER JOIN SHIPS S ON O.SHIP = S.NAME) T
ON C.CLASS = T.CLASS
WHERE C.COUNTRY = 'Gt.Britain'


SELECT S.STARNAME, N.NETWORTH, M.TITLE FROM MOVIEEXEC N
INNER JOIN MOVIE ON N.CERT# = M.PRODUCERC#
INNER JOIN STARSIN ON S.MOVIETITLE = M.TITLE
WHERE N.NAME IN (SELECT N1.NAME FROM MOVIEEXEC N1
WHERE N1.NETWORTH >= ANY(SELECT NETWORTH FROM MOVIEEXEC))

--zadachi
--1
SELECT M.TITLE , P.NAME
FROM MOVIE M
INNER JOIN MOVIEEXEC P ON P.CERT# = M.PRODUCERC#
WHERE P.NAME IN
(SELECT P1.NAME FROM MOVIEEXEC P1
INNER JOIN MOVIE M1 ON M1.PRODUCERC# = P1.CERT#
WHERE M1.TITLE = 'Star Wars')

--2
SELECT DISTINCT P.NAME FROM MOVIEEXEC P
INNER JOIN MOVIE M ON M.PRODUCERC# = P.CERT#
INNER JOIN STARSIN S ON S.MOVIETITLE = M.TITLE
WHERE S.STARNAME = 'Harrison Ford'

--3
SELECT S1.NAME, S2.STARNAME FROM STUDIO S1
INNER JOIN MOVIE M ON M.STUDIONAME = S1.NAME
INNER JOIN STARSIN S2 ON S2.MOVIETITLE = M.TITLE
--GROUP BY S1.NAME

--4
SELECT S.STARNAME, N.NETWORTH, M.TITLE FROM MOVIEEXEC N
INNER JOIN MOVIE M ON N.CERT# = M.PRODUCERC#
INNER JOIN STARSIN S ON S.MOVIETITLE = M.TITLE
WHERE N.NAME IN (SELECT N1.NAME FROM MOVIEEXEC N1
WHERE N1.NETWORTH >= ALL(SELECT NETWORTH FROM MOVIEEXEC))

--5
SELECT M1.NAME, S.MOVIETITLE FROM MOVIESTAR M1
LEFT OUTER JOIN STARSIN S ON S.STARNAME = M1.NAME
WHERE S.STARNAME IS NULL


--zadachi week 4
--1
SELECT P.MAKER,P.MODEL,P.TYPE FROM PRODUCT P
LEFT OUTER JOIN PC C1 ON C1.MODEL = P.MODEL
LEFT OUTER JOIN PRINTER C2 ON C2.MODEL = P.MODEL
LEFT OUTER JOIN LAPTOP C3 ON C3.MODEL = P.MODEL
WHERE C1.MODEL IS NULL AND C2.MODEL IS NULL AND C3.MODEL IS NULL

--2
SELECT P.MAKER FROM PRODUCT P
LEFT OUTER JOIN LAPTOP L ON L.MODEL = P.MODEL
LEFT OUTER JOIN PRINTER D ON D.MODEL = P.MODEL
GROUP BY MAKER
HAVING(COUNT(L.MODEL) >= 1 AND COUNT(D.MODEL) >= 1)

--3
SELECT L.HD FROM LAPTOP L
INNER JOIN PRODUCT P ON P.MODEL = L.MODEL
GROUP BY L.HD
HAVING(COUNT(P.MODEL) >= 2)

--4
SELECT * FROM PC P
LEFT OUTER JOIN PRODUCT P1 ON P1.MODEL = P.MODEL
WHERE P.MODEL IS NULL

--ships
--1
SELECT * FROM SHIPS S
INNER JOIN CLASSES C ON C.CLASS = S.CLASS

--2
SELECT * FROM SHIPS S
RIGHT OUTER JOIN CLASSES C ON C.CLASS = S.CLASS
WHERE C.CLASS IN (SELECT NAME FROM SHIPS)

--3
SELECT C.COUNTRY, S.NAME FROM CLASSES C
INNER JOIN SHIPS S ON S.CLASS = C.CLASS
LEFT OUTER JOIN OUTCOMES O ON O.SHIP = S.NAME
WHERE O.SHIP IS NULL

--4
SELECT S.NAME AS SHIPNAME FROM SHIPS S
INNER JOIN CLASSES C ON C.CLASS = S.CLASS
WHERE C.NUMGUNS >= 7 AND S.LAUNCHED = 1916

--5
SELECT S.NAME ,B.NAME, B.DATE FROM SHIPS S
INNER JOIN OUTCOMES O ON O.SHIP = S.NAME
INNER JOIN BATTLES B ON B.NAME = O.BATTLE
WHERE O.RESULT = 'sunk'

--6
SELECT S.NAME, C.DISPLACEMENT, S.LAUNCHED FROM SHIPS S
INNER JOIN CLASSES C ON C.CLASS = S.CLASS
WHERE S.CLASS = S.NAME

--7
SELECT C.CLASS,C.TYPE,C.COUNTRY,C.BORE,C.NUMGUNS,C.DISPLACEMENT FROM CLASSES C
LEFT OUTER JOIN SHIPS S ON S.CLASS = C.CLASS
WHERE S.CLASS IS NULL

--8
SELECT S.NAME ,C.NUMGUNS,C.DISPLACEMENT,O.RESULT FROM SHIPS S
INNER JOIN CLASSES C ON C.CLASS = S.CLASS
INNER JOIN OUTCOMES O ON O.SHIP = S.NAME
WHERE O.BATTLE = 'North Atlantic'
